name: 'Coverage Check'
description: 'Github Actions check that computes code coverage and fails the build if coverage drops.'
author: 'theScore Media'
inputs:
  coverage_report_path:
    required: true
    description: 'JSON file that contains coverage report'
  github_token:
    required: true
    description: 'Token used to create a check using Github API'
runs:
  using: 'node16'
  main: 'dist/index.js'
